---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - $(npm root -g)

node_js:
- '6'
- '5'

before_install:
- npm install -g yarn

install:
- yarn

script:
- npm run build
- npm run lint
- npm test
